SheetLog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('account_control.urls')),
    path('stock/',include('stock.urls')),
    path('account/',include('account_control.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
]

stock/urls.py
from django.urls import path
from stock.views.Item import views as item_views
from stock.views.Top_up import views as top_up_views
from stock.views.display import views as display_views
from stock.views.statement import views as statement_views
app_name = 'stock'
urlpatterns = [
    # Display
    path('',display_views.IndexView,name='index'),


    # Item
    path('item/create/',item_views.CreateView,name='create_item'),
    path('item/list/',item_views.ListView,name='list_item'),
    path('item/edit/<int:pk>/',item_views.EditView,name='edit_item'),

    # topup
    path('topup/',top_up_views.Top_up_View,name='create_top_up'),
    path('topup/list/',top_up_views.Top_up_List_View,name='list_top_up'),
    path('topup/edit/<int:pk>',top_up_views.Top_up_Edit_View,name='edit_top_up'),

    # statement
    path('create_statement/<int:pk>',statement_views.CreateView,name='create_statement'),
    path('list_statement/<int:form>/',statement_views.ListView,name='list_statement'),
    path('edit_statement/<int:form>/<int:pk>/',statement_views.EditView,name='edit_statement'),


    #test
    path('test/',display_views.testformView)

]

stock/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime


# Create your models here.
class Item(models.Model):
    objects: models.manager
    name = models.CharField(max_length=120)
    price = models.PositiveIntegerField()
    type = models.PositiveSmallIntegerField(choices=[(1, 'ticket'), (2, 'Air Pay'), (3, 'food')])

    def __unicode__(self):
        return self.name


class Sale(models.Model):
    objects: models.manager
    item = models.ForeignKey(Item,on_delete=models.CASCADE)
    volume = models.PositiveIntegerField()
    create_time = models.DateTimeField(auto_now=True)
    create_user = models.TextField(null=False)
    edit_time = models.DateTimeField(null=False)
    edit_user = models.TextField(null=False)


class LogSheet(models.Model):  # log sheet
    objects: models.manager
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    version = models.PositiveIntegerField()  # index by version
    value = models.PositiveIntegerField()
    date_log = models.DateTimeField(auto_now=True)


class TopUp(models.Model):  # fill up
    objects: models.manager
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    value = models.PositiveIntegerField()
    worker = models.CharField(max_length=200)
    version = models.PositiveIntegerField(default=0)
    date_log = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('stock:detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.item.name


class Income(models.Model):
    objects: models.manager
    name = models.CharField(max_length=200)
    value = models.PositiveIntegerField()
    date_log = models.DateTimeField(auto_now=True)


class Expense(models.Model):
    objects: models.manager
    name = models.CharField(max_length=200)
    value = models.PositiveIntegerField()
    date_log = models.DateTimeField(auto_now=True)


class TempExpense(models.Model):
    objects: models.manager
    name = models.CharField(max_length=200)
    value = models.PositiveIntegerField()
    date_log = models.DateTimeField()


# create model for template form
class DateTimeTemplate(models.Model):
    objects: models.manager
    date = models.DateField(default=datetime.now())
    time = models.TimeField(default=datetime.now())

    def get_absolute_url(self):
        return reverse('stock:getenddate',kwargs={'id': self.id})

stock/forms.py
from django import forms


class DateInput(forms.DateInput):
    type = 'date'


class InputTest(forms.Form):
    date = forms.DateField(widget=DateInput)

stock/views.py
# Move to stock/iryu folder

stock/views/Item/views.py
from django.shortcuts import render, redirect
from stock.models import Item
from stock.views.Item.Data2View import create,edit
from account_control.scripts.script import is_superior,account_permit


def CreateView(request):
    account_permit(request)
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    content = {}
    if request.method == 'POST':
        makenewitem = create(request)
        content['createnewitem'] = makenewitem
    return render(request, 'stock/Item/create.html', content)


def ListView(request):
    account_permit(request)
    content = {
        'items': Item.objects.all()
    }

    return render(request, 'stock/Item/list.html', content)


def EditView(request, pk=None):
    account_permit(request)
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    if id is not None:
        if request.POST:
            result = edit(request, pk)
            if result is not 'success' :
                content = {'item': Item.objects.get(id=pk),
                           'message': result}
                return render(request,'stock/Item/edit.html',content)
        elif Item.objects.filter(id=pk).count() == 1:
            content = {'item': Item.objects.get(id=pk)}
            return render(request, 'stock/Item/edit.html', content)
    return redirect('stock:list_item')

stock/views/Top_up/views.py
from django.shortcuts import render, redirect
from stock.models import Item, TopUp
from stock.views.Top_up.Data2View import list, top_up, edit
from account_control.scripts.script import is_superior


def Top_up_View(request):
    content = {'items': Item.objects.filter(type=3)}
    if request.POST:
        top_up(request)
        return redirect('stock:list_top_up')
    return render(request, 'stock/top_up/create.html', content)


def Top_up_List_View(request):
    content = list(request)
    return render(request, 'stock/top_up/list.html', content)


def Top_up_Edit_View(request, pk):
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    if TopUp.objects.filter(id=pk).count() == 1:
        content = {'top_up': TopUp.objects.get(id=pk)}
        if request.POST:
            result = edit(request, pk)
            if result == 'success':
                return redirect('stock:list_top_up')
            else:
                content['message'] = result
        return render(request, 'stock/top_up/edit.html', content)
    return redirect('stock:list_top_up')

stock/views/display/views.py
from django.shortcuts import render, redirect
from stock.models import Item
from account_control.models import UserStart
from .function import calculater,data2view
from django.utils import timezone
from account_control.scripts import script
from . import form

def IndexView(request):
    if not script.account_permit(request):  # check user permit before do other thing
        return redirect('account_control:logout')
    if request.POST:  # if Post Update data
        if 'startdate' in request.POST:
            content = calculater.text2date(request)
            return render(request, 'stock/display/index.html', content)
        else:
            data2view.setdisplay(request)
            content = calculater.normal_get_log(request)
            return render(request, 'stock/display/index.html', content)

    else:  # login and get view list
        if Item.objects.all().count() == 0:
            return redirect('stock:create_item')  # send to create item
        else:
            content = calculater.normal_get_log(request)
            return render(request, 'stock/display/index.html', content)


def testformView(request):
    if request.POST:
        login = form.loginform(request.POST)
        if login.is_valid():
            print(login.cleaned_data['name'])
    login = form.loginform()
    return render(request,'stock/test/test.html',{'form':login})

stock/views/statement/views.py
from django.shortcuts import render, redirect
from stock.models import Income, Expense, TempExpense
from account_control.models import UserStart
from .create import create, edit
from account_control.scripts.script import is_superior


def CreateView(request, pk):
    content = {
        'popup': 'popup_statement',
        'form': pk
    }
    if request.POST:
        result = create(request)
        if result == 'success-income':
            return redirect('stock:list_statement',1)
        elif result == 'success-expense':
            return redirect('stock:list_statement',2)
        elif result == 'success-temp':
            return redirect('stock:list_statement',3)
        else:
            content['message'] = result
    return render(request, 'stock/statement/create.html', content)


def EditView(request, form, pk):
    content = {
        'form': form
    }
    if not is_superior(request):
        return redirect('account_control:permit_denied')
    if form == 1:
        if Income.objects.filter(id=pk).count() == 0:
            return redirect('stock:list_statement',form=1)
        else:
            content["statement"] = Income.objects.get(id=pk)
    if form == 2:
        if Expense.objects.filter(id=pk).count() == 0:
            return redirect('stock:list_statement',form=2)
        else:
            content["statement"] = Expense.objects.get(id=pk)
    if form == 3:
        if TempExpense.objects.filter(id=pk).count() == 0:
            return redirect('stock:list_statement',form=3)
        else:
            content["statement"] = TempExpense.objects.get(id=pk)
    if request.POST:
        result = edit(request)
        if result == 'updated' or result == 'deleted':
            return redirect('stock:list_statement',form=form)
        else:
            content['message'] = result
    return render(request, 'stock/statement/edit.html', content)


def ListView(request, form):
    content = {
        'form': form,
        'title': 'hello'
               }
    worker = UserStart.objects.get(username=request.user)
    if form == 1:
        data = Income.objects.filter(date_log__gt=worker.date_log)
        content['lists'] = data
    elif form == 2:
        data = Expense.objects.filter(date_log__gt=worker.date_log)
        content['lists'] = data
    elif form == 3:
        data = TempExpense.objects.filter(date_log__gt=worker.date_log)
        content['lists'] = data
    return render(request, 'stock/statement/list.html', content)

stock/templates/stock/statement/create.html
{% extends 'stock/layout.html' %}
{%block content%}
{% if message %}
<div class="alert alert-danger" role="alert">
  {{message}}
</div>
{% endif %}
{% if form %}
<div class="container">
<form id="form" action="" method="post">
    {% csrf_token %}
    <div class="row">
        <p>รายการ</p>
        <p><input name="name" /><p>
    </div><div class="clr"></div>
    <div class="row">
        <p>ยอดเงิน</p>
        <p><input type="number" name="value" /><p>
    </div><div class="clr"></div>
    <div class="row">
        <p>ประเภท</p>
        <p id="type_selectd" >เลือกประเภท</p>
    </div><div class="clr"></div>
    <div class="row">
      <p><button type="button" onclick="history.go(-1)">Cancel</button></p>
      <p><button type="submit" >บันทึก</button></p>

    </div><div class="clr"></div>
  <div class="hidden_form">
    <input type="text" name="type" id="type" value="{{form}}">

  </div>
</form>
</div>


{% endif %}
{% endblock%}

{% block script %}
{% if popup %}
<script type="text/javascript">
  popup = '{{popup}}'
  viewpage()
</script>

{% endif %}
{% endblock script %}

stock/templates/stock/statement/edit.html
{% extends 'stock/layout.html'%}
{%block content%}
{% if message %}
<div class="message">{{message}}</div>
{% endif %}
{% if statement %}
<form action="" method="post" id="form">
<div class="container">
    {%csrf_token%}
    <div class="row">
      <p>รายการ</p>
      <p>{{statement.name}}</p>
    </div><div class="clr"></div>

    <div class="row">
      <p>ยอดเงิน</p>
      <p><input type="text" name="value" value="{{statement.value}}"></p>
    </div><div class="clr"></div>

    <div class="row">
      <p><button type="button" onclick="history.go(-1)">Cancel</button></p>
      <p><button type="submit" name="submit">Change</button></p>
    </div><div class="clr"></div>

    <div class="row">
      <p>Delete {{statement.name}}</p>
      <p><button type="button" onclick="verify('DELETE',event)">DELETE</button></p>
    </div><div class="clr"></div>

</div>

<div class="hidden_form">
    <input type="text" name="form" value="{{form}}">
    <input  type="hidden" name="statement_id" value="{{statement.id}}" />
    <input type="" name="form_verifypwd" id="form_verifypwd" value="">
    <button type="submit" name="DELETE" id="DELETE"></button>
</div>

</form>
{% endif %}
{%endblock%}

stock/templates/stock/statement/edit_income.html
{% extends 'stock/layout.html'%}
{%block content%}
{% if message %}
<div class="message">{{message}}</div>
{% endif %}
{% if income %}
<form action="" method="post" id="form">
<div class="container">
    {%csrf_token%}
    <div class="row">
      <p>รายการ</p>
      <p>{{income.name}}</p>
    </div><div class="clr"></div>

    <div class="row">
      <p>ยอดเงิน</p>
      <p><input type="text" name="value" value="{{income.value}}"></p>
    </div><div class="clr"></div>

    <div class="row">
      <p><button type="button" onclick="history.go(-1)">Cancel</button></p>
      <p><button type="submit" name="submit">Change</button></p>
    </div><div class="clr"></div>

    <div class="row">
      <p>Delete {{income.name}}</p>
      <p><button type="button" onclick="verify('DELETE',event)">DELETE</button></p>
    </div><div class="clr"></div>

</div>

<div class="hidden_form">
    <input  type="hidden" name="income_id" value="{{income.id}}" />
    <input type="" name="form_verifypwd" id="form_verifypwd" value="">
    <button type="submit" name="DELETE" id="DELETE"></button>
</div>

</form>
{% include 'stock/menu/popup.html' %}
{% endif %}
{%endblock%}

stock/templates/stock/statement/list.html
{% extends 'stock/layout.html' %}
{% block content %}
<div class="container">
{% if lists %}
    <table class="table">
      <tr>
        <th>วันที่</th>
        <th>รายการ</th>
        <th>จำนวน</th>
        <th>แก้ไข</th>
      </tr>
      {% for list in lists %}
      <tr>
        <td>{{list.date_log}}</td>
        <td>{{list.name}}</td>
        <td>{{list.value}}</td>
        <td><a href="{% url 'stock:edit_statement' form list.id  %}"><button>Edit</button></a></td>
      </tr>
      {% endfor %}
{% endif %}
    <tr>
        <td>
            <a class="btn btn-success" href="{% url 'stock:create_statement' form %}">เพิ่มรายการ</a>
        </td>

    </tr>



</table>
{% endblock %}